### ISSUE TITLE
Steam Deck Support?

### ISSUE THREAD

**Issue by TwoXTwentyOne** [Sergeanur/EaglePatch#10]
I went to **/home/deck/.local/share/Steam/steamapps/common/Assassins Creed/** and paste the dinput8.dll inside the directory and then created a **"scripts"** directory where I pasted the EaglePatchAC1.asi and EaglePatchAC1.ini.

then I started the game as usuall and I did not perceive any changes, I cannot use my playstation 4 controller without going into the control menu... :/

**Comment by Sergeanur** [comment]
No clue mate, don't own a Steam Deck

**Comment by TwoXTwentyOne** [comment]
That's too bad, it'd be great to get it working on that, Steam is great platform.

**Comment by goncharov** [comment]
@TwoXTwentyOne try adding a custom launch options `WINEDLLOVERRIDES="dinput8=n,b" %command%`. It helps for me

**Comment by TwoXTwentyOne** [comment]
OMG you're a hero... this 100% works!

@Sergeanur maybe that could be added to the notes, I assume the same for your AC2 mod :)

**Comment by TwoXTwentyOne** [comment]
This is resolved, please add @goncharov's solution to the config instruction of this patch :)
