### ISSUE TITLE
Ac 2 Eagle Patch 

### ISSUE THREAD

**Issue by TrashCat762** [Sergeanur/EaglePatch#15]
I am having trouble following the guide and I would like a video or further detailed explanation as to the setup as I am new to all of this.

**Comment by Nisekoi-1** [comment]
1. **Download Ultimate ASI Loader:** Go to [https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/v4.68/ and download the file named "Ultimate-ASI-Loader.zip](https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases/download/v4.68/Ultimate-ASI-Loader.zip)".

2. **Extract Ultimate ASI Loader:** Extract the contents of the downloaded zip file. You should find a file named `dinput8.dll`.

3. **Place dinput8.dll:** Copy the `dinput8.dll` file into your Assassin's Creed II directory. This directory is typically located where your game is installed.

4. **Create scripts folder:** Inside your Assassin's Creed II directory, create a new folder named "scripts".

5. **Download Eagle Patch:** Download EaglePatchAC2.asi and EaglePatchAC2.ini from releases
6. **Place files in scripts folder:** Move the downloaded `EaglePatchAC2.asi` and `EaglePatchAC2.ini` files into the newly created "scripts" folder.
