### ISSUE TITLE
EaglePatch Causes the game to not detect the Xbox controller correctly - Assassin's Creed 2.

### ISSUE THREAD

**Issue by HelderRocket** [Sergeanur/EaglePatch#5]
Testing EaglePatch, I notice that when I go to the controls option, "Xinput Controller 1" appears in the list, instead of the name of my controller "Controller (Xbox One For Windows)".

And when I want to customize them, when I click on a function, and press a button on the controller, nothing happens. I have an original Xbox Series controller, which is wired to the computer.

Without the patch, it is detected correctly and with its respective name (as I mentioned before), but with it activated, the controller only works in the menu. And there is no other controller in the list.

That controller appears in the list even if no controller is connected to the computer. (Xinput Controller 1).

Before the patch:
![AssassinsCreedIIGame_2023_06_10_11_12_30_977](https://github.com/Sergeanur/EaglePatch/assets/104467221/b96cd3bc-7e62-43b0-ba0f-10a13f065b6b)

After the patch:
![AssassinsCreedIIGame_2023_06_10_11_14_42_550](https://github.com/Sergeanur/EaglePatch/assets/104467221/0a987738-707c-40c0-80f2-672d442cb6dc)

**Comment by Sergeanur** [comment]
This is by design.
