### ISSUE TITLE
EaglePatch AC2 compatible with Steam?

### ISSUE THREAD

**Issue by ShinChaosBahamut** [Sergeanur/EaglePatch#6]
As the title asks, can the AC2 EaglePatch be used on the Steam version of the game, or does it have to be the UPlay-bought version?

**Comment by TwoXTwentyOne** [comment]
I second that, would love for it to work via Steam or even Steam Deck!

**Comment by TwoXTwentyOne** [comment]
Check #10

**Comment by Zorklis** [comment]
Yes it works with Steam version. this can be closed.
